In [7]:
weight = 0.1
def neural_network(input_, weight):
    prediction= input_ * weight
    return prediction

In [8]:
number_of_toes = [8.5, 9.5, 10, 9]
input_ = number_of_toes[0]
pred = neural_network(input_, weight)
print(pred)

0.8500000000000001


In [9]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] *b[i])
        
    return output

def neural_network(input_, output):
    pred = w_sum(input_, weights)
    
    return pred


In [10]:
weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2,1.3, 0.5, 1.0]

input_ = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input_, weights)

print(pred)

0.9800000000000001


## Beginning to use Numpy for writing Neural Networks 

In [11]:
import numpy as np

In [12]:
weights = np.array([0.1, 0.2, 0])

def np_neural_network(inputs, weights):
    pred = inputs.dot(weights)
    
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0], wlrec[0], nfans[0]])
pred = np_neural_network(inputs, weights)

print(pred)

0.9800000000000001


## Creating a Neural Network with Multiple Outputs

In [13]:
def ele_mul(number, vector):
    output = [0,0,0]
    
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number *vector[i]
        
    return output

def neural_network(inputs, weights):
    pred = ele_mul(inputs, weights)
    
    return pred


In [15]:
wlrec= [0.65, 0.8, 0.8,0.9]

inputs = wlrec[0]

pred = neural_network(inputs, weights)

print(pred)

[0.065, 0.13, 0.0]


In [17]:
def w_sum(a,b):
    assert(len(a) == len(b))
    
    output=0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output=[0,0,0]
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
        
    return output

def neural_network(inputs, weights):
    pred = vect_mat_mul(inputs, weights)
    
    return pred


In [23]:
ih_wgt = [[0.1, 0.2, -0.1],
         [-0.1, 0.1, 0.9],
         [0.1, 0.4, 0.1] ]

hp_wgt = [[0.3, 1.1, -0.3],
         [0.1, 0.2, 0.0],
         [0.0, 1.3, 0.1] ]

weights = [ih_wgt, hp_wgt]

def neural_network(inputs, weights):
    hid = vect_mat_mul(inputs, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    
    return pred

In [24]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(inputs, weights)
print (pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [26]:
import numpy as np

ih_wgt = np.array([
    [0.1, 0.2, -0.1],
    [-0.1, 0.1, 0.9],
    [0.1, 0.4, 0.1]]).T

hp_wgt = np.array([
    [0.3, 1.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]]).T

weights = [ih_wgt, hp_wgt]

def neural_network(inputs, weights):
    hid = inputs.dot(weights[0])
    pred = hid.dot(weights[1])
    
    return pred
toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
 
inputs = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(inputs, weights)

print(pred)

[0.2135 0.145  0.5065]


In [30]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3,],
             [4,5,6,7]])

d  = np.zeros((2,4))
e = np.random.rand(2,5)

print(a)
print(b)
print(c)
print(d)
print(d)



[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
print(a*0.1)

[0.  0.1 0.2 0.3]


In [32]:
print(c*0.2)

[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]


In [33]:
print(a*b)

[ 0  5 12 21]


In [34]:
print(a*b*0.2)

[0.  1.  2.4 4.2]


In [35]:
print(a*c)

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [36]:
print(a*e)

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [37]:
knob_weight = 0.5
input = 0.5
goal_pred = 0.8

pred = input * knob_weight

error = (pred - goal_pred) ** 2 

print(error)

0.30250000000000005
